### ISSUE TITLE
Add P828 - has cause - to the dropdown

### ISSUE THREAD

**Issue by Ainali** [ogroppo/entitree#116]
It would be very nice to use this to see causality links. Something that caused something, which in turn caused something else and so on.

**Comment by mshd** [comment]
Hi Jan, thanks for opening an issue. All properties should be listed, "has cause" should be there (maybe a bit lower in the dropdown), if it has any links to. See [here](https://www.entitree.com/en/has_cause/Childbirth). Can you find it on your end?

**Comment by Ainali** [comment]
In that view I can see it. But if I select one of the examples it disappear from the list, and the list contains around 50 properties.

**Comment by mshd** [comment]
Ok we'll look into it. Can you share the item you have to search for?

**Comment by Ainali** [comment]
Ah, now I get it! The dropdown only shows the properties on the item. I was thinking backwards and didn't care about items, I just wanted to start exploring based on the property. This issue can be closed :blush:

**Comment by mshd** [comment]
I guess we should make it clearer how to operate the website.
