### ISSUE TITLE
Other Wikidata properties with biographies than Geni Wikitree

### ISSUE THREAD

**Issue by salgo60** [ogroppo/entitree#142]
Thanks for en excellent tool is there an possibility in the popup window get more than Wikitree Geni?   

We have in Wikidata also biographies in properties
* [Property:P4963](https://www.wikidata.org/wiki/Property:P4963) swedish and english
* [Property:P3217](https://www.wikidata.org/wiki/Property:P3217) swedish
* author with books in [Property:P5101](https://www.wikidata.org/wiki/Property:P5101)

**Comment by mshd** [comment]
Hi Magnus thanks for the interest in our project, I think for now we have enough external identifiers, the ones you mentioned are only present for a few thousand people. Users can still select Wikidata and then find the Swedish biographical websites.
