### ISSUE TITLE
Filter out disambiguation pages from the search results dropdown

### ISSUE THREAD

**Issue by ogroppo** [ogroppo/entitree#19]
Currently used search dropdown API: https://www.wikidata.org/w/api.php?action=help&modules=wbsearchentities
Example: https://www.wikidata.org/w/api.php?action=wbsearchentities&search=Particle&language=en

**Comment by mshd** [comment]
According to [most](https://query.wikidata.org/#%23%0ASELECT%20%3Fitem%20%3FitemLabel%20%3FitemDescription%0AWHERE%20%0A%7B%0A%20%20%3Fitem%20wdt%3AP31%20wd%3AQ4167410.%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22en%22.%20%7D%0A%7D%0ALIMIT%2010%0A) disambiguation pages the description is always the same. Other indicators cannot be found.
However, for each language the description will be different

**Comment by mshd** [comment]
@ogroppo Any reason why the searchBar.js is so long?

**Comment by ogroppo** [comment]
long?

**Comment by mshd** [comment]
just seemed to me that way

**Comment by ogroppo** [comment]
I does a lot of stuff... have a look at https://github.com/ogroppo/wikiforest/commit/1aedb1c49ee3dec5420a79cf2f4d42d900c84dc9 @mshd and let me know what you think
