### ISSUE TITLE
Linking to expanded tree

### ISSUE THREAD

**Issue by jkjkjkjkjk** [ogroppo/entitree#209]
It would be nice to have a feature to link the collapsed tree as well, for example url/a/3 (three generations of ancestors expanded) or url/d/3 (three generations of descendants expanded).

**Comment by ogroppo** [comment]
Sure! For whoever implements this, please use query params e.g.`https://www.entitree.com/en/family_tree/Elizabeth_II?d=2&a=3`

**Comment by ogroppo** [comment]
Done. Example here -> `https://www.entitree.com/en/family_tree/Barack_Obama?Q15982330=u&Q15982394=u&Q2856335=u&Q649593=u&Q766106=u`
