### ISSUE TITLE
Wikibase and entitree

### ISSUE THREAD

**Issue by kerphi** [ogroppo/entitree#236]
Entitree is wikidata based.
Wikidata is wikibase based.

Could entitree be connected to a generic wikibase?

**Comment by mshd** [comment]
Yes certainly, it shouldn't be too much work inserting a new base_url and changing property ids.
But is there any use case? do you have a wikibase with significant data. For now, I'd say we better use Wikidata.

**Comment by kerphi** [comment]
Great!
And yes I will have a big wikibase and I was wondering if entitree could be a way to show data.

My use case is bibliographic data. A big wikibase is under construction at a national level in France to host and manage lot of entities related to bibliography: persons, works, concepts, events, places...
You can have details here: https://www.transition-bibliographique.fr/fne/french-national-entities-file/

**Comment by mshd** [comment]
Yes, we will certainly consider integrating it when it becomes available, alternatively, you may also commit a PR. However, especially when it comes to people, it would be great to use Wikidata as main source, and then later link your database with your Wikidata.

**Comment by mshd** [comment]
@kerphi do you have any further question?

**Comment by kerphi** [comment]
No and thanks for your advices.
