### ISSUE TITLE
URL rewrite for static build

### ISSUE THREAD

**Issue by waldenn** [ogroppo/entitree#241]
Hi, what is the URL-rewrite I should use to make the static build work correctly?

This URL shows the app correctly: https://tree.conze.pt

However, the following URL does not work (without some URL data mapping to an entry point behind the scenes): https://tree.conze.pt/en/family_tree/Sudono_Salim

I could use the dynamic build, but would prefer getting the static build working if possible.

An option to just use plain URL-parameters would be even easier, like eg.: https://tree.conze.pt?lang=en&type=family_tree&id=Sudono_Salim

Thanks!

**Comment by mshd** [comment]
Hi, are you running the server or just the _npm run dev_, did you follow the readme steps?

**Comment by waldenn** [comment]
> Hi, are you running the server or just the _npm run dev_, did you follow the readme steps?

Hi, I'm only running the "npm run build" output, not the server currently. If I read the README correctly, a running server is currently required?

**Comment by mshd** [comment]
It should be running client-side also, the server just tweaks a few html meta tags. I think if you run the server it would work. But I'll ask my friend, why it's not running properly on the client-side. Please hold on.

**Comment by waldenn** [comment]
> It should be running client-side also, the server just tweaks a few html meta tags. I think if you run the server it would work. But I'll ask my friend, why it's not running properly on the client-side. Please hold on.

Great. Side note: I would like to make a donation to your project, could you please also activate GitHub Sponsors (or use something similar)?

**Comment by ogroppo** [comment]
Hi @waldenn, are you using apache or nginx? in your case yes you don't need to run the server because that's used only for Server Side Rendering (SSR) to make google and others happy.
If you want to contribute, just visit https://www.entitree.com/about and you'll find paypal donation buttons. Thanks!

**Comment by waldenn** [comment]
> Hi @waldenn, are you using apache or nginx? in your case yes you don't need to run the server because that's used only for Server Side Rendering (SSR) to make google and others happy.
> If you want to contribute, just visit https://www.entitree.com/about and you'll find paypal donation buttons. Thanks!

Hey! I just donated, thanks for all your work on this beautiful tree-viewing tool!

I'm using Apache, but the URL parameters need are not passed on to the app currently. I was wondering what I could do to fix that?

Else, using pure URL-parameters is an option (but that then requires to data paths to maintain).

Thanks again!

**Comment by ogroppo** [comment]
Much appreciated! How does your .htaccess look like? probably want to have a look at this setup https://gist.github.com/ywwwtseng/63c36ccb58a25a09f7096bbb602ac1de

Anyway, you could also use entitree in an iframe and that would solve the hassle of setting the project up in your website, although you won't be able to search because the header is hidden.

Let us know

**Comment by waldenn** [comment]
> Much appreciated! How does your .htaccess look like? probably want to have a look at this setup https://gist.github.com/ywwwtseng/63c36ccb58a25a09f7096bbb602ac1de

Welcome! I have various rewrite rules in place already, but I think I'll need to hack in some kind of parameter support, to allow the react code to see the incoming data parameters (from plain URL params).

I personally don't like the by-default pretty-URL setup (that should be optional IMHO), as it makes integrations harder. Plain URL-parameters are the web-way of sharing data between app-links.

> Anyway, you could also use entitree in an iframe and that would solve the hassle of setting the project up in your website, although you won't be able to search because the header is hidden.

I already use Entitree this way currently, but I would like to have some more control over the integration with self-hosting. Will look more into this as time allows. Thanks!
