### ISSUE TITLE
Add language select, language variable functions

### ISSUE THREAD

**Issue by mshd** [ogroppo/entitree#31]

**Comment by mshd** [comment]
https://github.com/ogroppo/wikiforest/commit/1aedb1c49ee3dec5420a79cf2f4d42d900c84dc9

**Comment by mshd** [comment]
nice there are quite a lot of languages a search bar will be useful
where should the language saved, in the session or url?

**Comment by ogroppo** [comment]
I'd say localstorage

**Comment by ogroppo** [comment]
So from now now I'd say lang is always an object that looks like {code, name, disambPageDesc}, so if something is lang code, we will call it langCode
