### ISSUE TITLE
Can't load too many images at the same time (50?)

### ISSUE THREAD

**Issue by ogroppo** [ogroppo/entitree#36]
Given we have the ability to fetch many items in short time, we run the risk to display a number of nodes that could all trigger a get request for the image (thumbnail) and this will result in an annoying 429 error from https://upload.wikimedia.org/wikipedia/commons.

This problem needs also to be taken in consideration if we want to show expanded trees already, via link for example, which can easily have more than 50 nodes at any position.

This could be address in 2 ways:
- Rendering 50 nodes every 1? second with a setTimeout (not hard to handle in react)
- Implement a sort of "paginated" children/parents level where at the most you see 5-10 nodes and buttons to see prev/next group... this will not address: printing (nodes will be hidden), the fact that more than 50 node could be still be around the whole page

**Comment by mshd** [comment]
https://phabricator.wikimedia.org/T241644

**Comment by ogroppo** [comment]
oh have a look at this line https://github.com/ogroppo/wikiforest/pull/37/files#diff-048667767d32341eda71649bc9869f66R36... it seems to work by loading 50 images at the time in 500 mils, obviously does not cover some edge cases like both parents and children opening nodes because it's based on the index of the node

**Comment by mshd** [comment]
ogroppo alread fixed it
