### ISSUE TITLE
Find alternative for unlaballed items

### ISSUE THREAD

**Issue by mshd** [ogroppo/entitree#39]
http://localhost:3000/?p=P279&q=Q4498085
Maybe use 5 main languages as a default? de,fr,es,nl,it

**Comment by ogroppo** [comment]
Good shout

**Comment by mshd** [comment]
http://localhost:3000/?p=P40&q=Q3752663 it's showing German description if the english one is not availible

**Comment by ogroppo** [comment]
I don't get this, what's the bug and on what node?

**Comment by mshd** [comment]
I haven't looked into it, what I mean is that there should be no fallback description

**Comment by ogroppo** [comment]
moved add* functions in own file and applied separate logic for label and desc
