### ISSUE TITLE
add children sort

### ISSUE THREAD

**Issue by ogroppo** [ogroppo/entitree#4]
from oldest (left) to youngest (right)

**Comment by ogroppo** [comment]
possibly apply the same logic to siblings? what about spouses?

**Comment by mshd** [comment]
yes spouses of course sorted by "start date" aka date of marriage

**Comment by ogroppo** [comment]
@mshd But I guess the most recent spouse should be on the left? (closest to the node) so the order should de DESC?

**Comment by mshd** [comment]
I would choose Ascending, but I guess we can decide that later, first there should be some kind of order

**Comment by ogroppo** [comment]
Sorting done against brithDate for children, siblings and startDate for spouses... Tested with some BCE dates as well and seems to work
