### ISSUE TITLE
Add option select

### ISSUE THREAD

**Issue by mshd** [ogroppo/entitree#42]

**Comment by ogroppo** [comment]
Both people I showed the app thought that the language dropdown was for the whole interface, and they don't that the external (wiki)data applies only to labels, descriptions and props (will add an issue for dates, moment should handle 'locale' but I won't expect all those languages be available though). Perhaps you could put the language dropdown in the settings modal and put the slider icon in the header? It will diminish slightly the importance of the language selection but at least it would have a label clearly stating "apply language where possible" or similar.

**Comment by ogroppo** [comment]
Hi Martin, made this bit this morning. Have a go at setting sex colour 😎
