### ISSUE TITLE
Multi-Line Truncation for the description

### ISSUE THREAD

**Issue by mshd** [ogroppo/entitree#70]
The description is usually longer than one line, so it should be shown in 2 lines

**Comment by mshd** [comment]
http://hackingui.com/front-end/a-pure-css-solution-for-multiline-text-truncation/
It just works for modern browsers, but I think we can neglect others (like old Internet Explorers)

**Comment by ogroppo** [comment]
<img width="419" alt="Screenshot 2020-07-09 at 13 11 00" src="https://user-images.githubusercontent.com/4820803/87038481-b49bc380-c1e5-11ea-84e7-042061b7d2f2.png">

no space for the birthplace now though

**Comment by mshd** [comment]
@ogroppo how do you like the four-line clamp, more efficient space management haha

**Comment by ogroppo** [comment]
can you add a screenshot please, my code is an exploding nuclear bomb at the minute 😁

**Comment by mshd** [comment]
![Screenshot from 2020-07-15 21-49-25](https://user-images.githubusercontent.com/17379661/87589134-13c96e80-c6e5-11ea-8d8f-fead09b8e68c.png)

**Comment by ogroppo** [comment]
I think it's a great idea because it will maximise space usage, in some cases the title will obliterate the description but not a common case I think. 👍
