### ISSUE TITLE
Fix kilo million billion dates

### ISSUE THREAD

**Issue by ogroppo** [ogroppo/entitree#75]

**Comment by ogroppo** [comment]
@mshd have a look at this commit, tries to show life span, or start-end dates, or inception-abolished in the date line

**Comment by mshd** [comment]
Yes inception-abolished makes sense, although it's not clear in the mode what number it is. and personally, it's a bit over-kill with files. For the other dates, I have never come across any case like it, but I trust you that it works. Would be nice to have real node test case for these things.

**Comment by ogroppo** [comment]
> it's not clear in the mode what number it is 
I don't get this?

Do you mean it doesn't say: "Inception: 1943 - ..."

**Comment by ogroppo** [comment]
we could use this label for translation https://www.wikidata.org/wiki/Q7854897 but has just few languages in it, an some don't use the abbreviation so gets too long

**Comment by ogroppo** [comment]
https://www.wikidata.org/wiki/Q3013059, Kiloannum 😂😂😂😂 can't stop laughing

**Comment by mshd** [comment]
I think it works for the most part.
