### ISSUE TITLE
Add a recenter button in details modal as well

### ISSUE THREAD

**Issue by ogroppo** [ogroppo/entitree#83]

**Comment by mshd** [comment]
Done

**Comment by ogroppo** [comment]
Where is the commit referencing this issue?

**Comment by mshd** [comment]
Oh sorry I misread, it's not done

**Comment by ogroppo** [comment]
I'll do it, promised ;)

**Comment by ogroppo** [comment]
as promised, done!

**Comment by ogroppo** [comment]
<img width="555" alt="Screenshot 2020-09-27 at 13 39 32" src="https://user-images.githubusercontent.com/4820803/94365216-e1fe5c00-00c6-11eb-9b84-b633ab82ac4d.png">

Note that the icon in the "Navigation" buttons does not reload the tree anymore, it just centers the graph as one would expect (I guess)
