### ISSUE TITLE
Import images from Images Database

### ISSUE THREAD

**Issue by mshd** [ogroppo/entitree#90]
Use database and project https://github.com/mshd/image-database-express
To import missing images

**Comment by mshd** [comment]
Finally got it up and running on SSL https://images.dataprick.com/

**Comment by ogroppo** [comment]
Told you to google it!!!

**Comment by ogroppo** [comment]
Does the image server url need to be mentioned on the website?

**Comment by mshd** [comment]
Yes where else? Google what?

**Comment by ogroppo** [comment]
> Yes where else?
Are we talking about the same thing, I mean to tell the user in the about page or something.

> Google what?
How to fix your apache 😂😂😂

**Comment by mshd** [comment]
Ah ok, no but the website is not quite user-friendly yet, I'll do that first. Yes I was able to fix my apache
