### ISSUE TITLE
Add options birth name and toggle icons

### ISSUE THREAD

**Issue by mshd** [ogroppo/entitree#93]
Birth name
and toggle icons

**Comment by mshd** [comment]
@ogroppo How to fix show/hide nodeBirthName class?

**Comment by mshd** [comment]
Idea:

- Hide adopted chilrend/only show adopted parent
- Hide children which died young (Totgeburt)

**Comment by ogroppo** [comment]
Only example that comes to my mind is https://www.entitree.com/en/family_tree/Henry_VIII, children have a mixed significant event that could be filtered
